version: '3'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: "anshay123/cliassignment:latest"
    ports:
      - "3001:3001"
    env_file:
      - ./a.env
  frontend:
    build:
      context: ./assignment1
      dockerfile: ./assignment1/Dockerfile
    image: "anshay123/frontend:latest"
    ports:
      - "3000:3000"
    links:
      - "backend:be"